# Generated by Django 5.1.1 on 2024-09-18 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtlantaFoodFinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='last_update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='location',
            name='contact_info',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='location',
            name='cuisine_type',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='location',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
