# Generated by Django 5.1.1 on 2024-09-21 19:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtlantaFoodFinder', '0002_location_last_update_date_alter_location_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AddField(
            model_name='review',
            name='review_id',
            field=models.CharField(default='', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AtlantaFoodFinder.location'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.CharField(default='', max_length=128),
        ),
    ]
